# Generated by Django 5.0.2 on 2025-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sale_saleitem_sale_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
