# Generated by Django 5.0.2 on 2025-01-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_saleitem_price_at_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='dollar_rate_at_sale',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
            preserve_default=False,
        ),
    ]
