# Generated by Django 5.0.2 on 2025-11-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_settings_options_product_retail_sale_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.classification'),
        ),
    ]
