# Generated by Django 5.0.2 on 2025-11-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_saleitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.classification'),
        ),
    ]
