# Generated by Django 5.0.2 on 2025-11-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Dealer Name')),
                ('contact_info', models.TextField(blank=True, verbose_name='Contact Information')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Current Financial Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('P', 'Purchase'), ('T', 'Payment')], max_length=1, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='store.trader', verbose_name='Trader')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
